# Generated by Django 4.2.9 on 2024-01-07 16:50

import apps.base.utils
import apps.course.models
from django.db import migrations, models
import django.db.models.deletion
import hitcount.models
import modelcluster.contrib.taggit
import modelcluster.fields
import wagtail.blocks
import wagtail.contrib.table_block.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("wagtailcore", "0089_log_entry_data_json_null_to_object"),
        ("wagtailimages", "0025_alter_image_file_alter_rendition_file"),
        ("base", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CourseHome",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "short_description",
                    models.TextField(blank=True, null=True, verbose_name="간략한 설명"),
                ),
                (
                    "content",
                    wagtail.fields.StreamField(
                        [
                            (
                                "banner",
                                wagtail.blocks.StructBlock(
                                    [
                                        (
                                            "slides",
                                            wagtail.blocks.StreamBlock(
                                                [
                                                    (
                                                        "slide",
                                                        wagtail.blocks.StructBlock(
                                                            [
                                                                (
                                                                    "image",
                                                                    wagtail.images.blocks.ImageChooserBlock(
                                                                        label="이미지"
                                                                    ),
                                                                ),
                                                                (
                                                                    "description",
                                                                    wagtail.blocks.RawHTMLBlock(
                                                                        label="HTML",
                                                                        required=False,
                                                                    ),
                                                                ),
                                                            ],
                                                            label="슬라이드",
                                                        ),
                                                    )
                                                ],
                                                collapsed=True,
                                                label="슬라이드",
                                            ),
                                        ),
                                        (
                                            "height",
                                            wagtail.blocks.ChoiceBlock(
                                                choices=[
                                                    ("300", "300px"),
                                                    ("400", "400px"),
                                                    ("500", "500px"),
                                                    ("600", "600px"),
                                                    ("700", "700px"),
                                                    ("800", "800px"),
                                                ],
                                                label="슬라이더 높이 px",
                                            ),
                                        ),
                                        (
                                            "fit_container",
                                            wagtail.blocks.BooleanBlock(
                                                label="container에 맞추기", required=False
                                            ),
                                        ),
                                    ],
                                    label="배너",
                                    required=False,
                                ),
                            ),
                            (
                                "richtext",
                                wagtail.blocks.RichTextBlock(
                                    label="에디터", required=False
                                ),
                            ),
                            (
                                "html",
                                wagtail.blocks.RawHTMLBlock(
                                    label="HTML 코드", required=False
                                ),
                            ),
                        ],
                        blank=True,
                        null=True,
                        use_json_field=True,
                        verbose_name="내용",
                    ),
                ),
                (
                    "cover",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="wagtailimages.image",
                        verbose_name="커버",
                    ),
                ),
            ],
            options={
                "verbose_name": "과정",
                "verbose_name_plural": "과정",
            },
            bases=("wagtailcore.page",),
        ),
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "content",
                    wagtail.fields.StreamField(
                        [
                            (
                                "banner",
                                wagtail.blocks.StructBlock(
                                    [
                                        (
                                            "slides",
                                            wagtail.blocks.StreamBlock(
                                                [
                                                    (
                                                        "slide",
                                                        wagtail.blocks.StructBlock(
                                                            [
                                                                (
                                                                    "image",
                                                                    wagtail.images.blocks.ImageChooserBlock(
                                                                        label="이미지"
                                                                    ),
                                                                ),
                                                                (
                                                                    "description",
                                                                    wagtail.blocks.RawHTMLBlock(
                                                                        label="HTML",
                                                                        required=False,
                                                                    ),
                                                                ),
                                                            ],
                                                            label="슬라이드",
                                                        ),
                                                    )
                                                ],
                                                collapsed=True,
                                                label="슬라이드",
                                            ),
                                        ),
                                        (
                                            "height",
                                            wagtail.blocks.ChoiceBlock(
                                                choices=[
                                                    ("300", "300px"),
                                                    ("400", "400px"),
                                                    ("500", "500px"),
                                                    ("600", "600px"),
                                                    ("700", "700px"),
                                                    ("800", "800px"),
                                                ],
                                                label="슬라이더 높이 px",
                                            ),
                                        ),
                                        (
                                            "fit_container",
                                            wagtail.blocks.BooleanBlock(
                                                label="container에 맞추기", required=False
                                            ),
                                        ),
                                    ],
                                    label="배너",
                                    required=False,
                                ),
                            ),
                            (
                                "richtext",
                                wagtail.blocks.RichTextBlock(
                                    label="에디터", required=False
                                ),
                            ),
                            (
                                "html",
                                wagtail.blocks.RawHTMLBlock(
                                    label="HTML 코드", required=False
                                ),
                            ),
                        ],
                        blank=True,
                        null=True,
                        use_json_field=True,
                        verbose_name="내용",
                    ),
                ),
                ("priority", models.IntegerField(default=0, verbose_name="상단 정렬")),
                (
                    "external_link",
                    models.URLField(
                        blank=True, max_length=254, null=True, verbose_name="외부 링크"
                    ),
                ),
                (
                    "allow_rating",
                    models.BooleanField(default=False, verbose_name="추천 사용하기"),
                ),
                (
                    "allow_comments",
                    models.BooleanField(default=False, verbose_name="댓글 사용하기"),
                ),
                (
                    "number",
                    models.CharField(
                        default=apps.course.models.random_number,
                        max_length=50,
                        unique=True,
                        verbose_name="과정 코드",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="잛은 설명"),
                ),
                ("target", models.TextField(blank=True, null=True, verbose_name="대상")),
                (
                    "objective",
                    models.TextField(blank=True, null=True, verbose_name="학습목표"),
                ),
                (
                    "grading",
                    models.TextField(blank=True, null=True, verbose_name="평가 방법"),
                ),
                (
                    "created_date",
                    models.DateField(blank=True, null=True, verbose_name="출시 날짜"),
                ),
                (
                    "preview",
                    models.URLField(blank=True, null=True, verbose_name="미리보기"),
                ),
                (
                    "contents",
                    models.TextField(blank=True, null=True, verbose_name="목차"),
                ),
                (
                    "effort",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="학습 시간"
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="레벨"
                    ),
                ),
                (
                    "ncs_unit",
                    models.CharField(
                        blank=True, max_length=254, null=True, verbose_name="NCS 분류"
                    ),
                ),
                (
                    "tuition_assistances",
                    wagtail.fields.StreamField(
                        [
                            (
                                "tuition_assistance",
                                wagtail.blocks.StructBlock(
                                    [
                                        (
                                            "policy",
                                            wagtail.blocks.CharBlock(label="교육비 지원 제도"),
                                        ),
                                        (
                                            "assistance",
                                            wagtail.contrib.table_block.blocks.TableBlock(
                                                label="지원 내용"
                                            ),
                                        ),
                                    ]
                                ),
                            )
                        ],
                        blank=True,
                        null=True,
                        use_json_field=True,
                        verbose_name="교육비 지원",
                    ),
                ),
                (
                    "tutors",
                    wagtail.fields.StreamField(
                        [
                            (
                                "tutor",
                                wagtail.blocks.StructBlock(
                                    [
                                        (
                                            "image",
                                            wagtail.images.blocks.ImageChooserBlock(
                                                label="사진", required=False
                                            ),
                                        ),
                                        ("name", wagtail.blocks.CharBlock(label="이름")),
                                        (
                                            "bio",
                                            wagtail.blocks.RichTextBlock(
                                                label="바이오", required=False
                                            ),
                                        ),
                                    ]
                                ),
                            )
                        ],
                        blank=True,
                        null=True,
                        use_json_field=True,
                        verbose_name="교강사",
                    ),
                ),
                (
                    "textbooks",
                    wagtail.fields.StreamField(
                        [
                            (
                                "textbook",
                                wagtail.blocks.StructBlock(
                                    [
                                        ("title", wagtail.blocks.CharBlock(label="제목")),
                                        (
                                            "author",
                                            wagtail.blocks.CharBlock(label="저자"),
                                        ),
                                        (
                                            "publisher",
                                            wagtail.blocks.CharBlock(label="출판사"),
                                        ),
                                        (
                                            "published_date",
                                            wagtail.blocks.DateBlock(
                                                label="출간일", required=False
                                            ),
                                        ),
                                        (
                                            "isbn",
                                            wagtail.blocks.CharBlock(label="ISBN"),
                                        ),
                                        (
                                            "price",
                                            wagtail.blocks.IntegerBlock(label="가격"),
                                        ),
                                    ]
                                ),
                            )
                        ],
                        blank=True,
                        null=True,
                        use_json_field=True,
                        verbose_name="교재",
                    ),
                ),
                (
                    "esimsa_code",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        validators=[apps.base.utils.validate_esimsa_code],
                        verbose_name="esimsa 코드",
                    ),
                ),
                (
                    "esimsa_code_expiration",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="과정 승인 만료"
                    ),
                ),
                (
                    "categories",
                    modelcluster.fields.ParentalManyToManyField(
                        blank=True, to="base.category", verbose_name="카테고리"
                    ),
                ),
                (
                    "cover",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="wagtailimages.image",
                        verbose_name="커버",
                    ),
                ),
                (
                    "tags",
                    modelcluster.contrib.taggit.ClusterTaggableManager(
                        blank=True,
                        help_text="A comma-separated list of tags.",
                        through="base.TaggedPageItem",
                        to="base.Tag",
                        verbose_name="태그",
                    ),
                ),
            ],
            options={
                "verbose_name": "과정",
                "verbose_name_plural": "과정",
            },
            bases=("wagtailcore.page", hitcount.models.HitCountMixin),
        ),
    ]
