"""
Django settings for portal project.

Generated by 'django-admin startproject' using Django 4.2.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
import os
from pathlib import Path

from import_export.formats.base_formats import XLSX
from import_export.tmp_storages import CacheStorage


PROJECT_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
BASE_DIR = os.path.dirname(PROJECT_DIR)


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/


# Application definition

INSTALLED_APPS = [
    "wagtail.contrib.forms",
    "wagtail.contrib.redirects",
    "wagtail.contrib.table_block",
    "wagtail.embeds",
    "wagtail.sites",
    "wagtail.users",
    "wagtail.snippets",
    "wagtail.documents",
    "wagtail.images",
    "wagtail.search",
    "wagtail.admin",
    "wagtail",
    "modelcluster",
    "taggit",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.postgres",
    "django.contrib.humanize",
    "django.contrib.sites",
    "hitcount",
    "colorfield",
    "treenode",
    "django_ace",
    "crispy_forms",
    "crispy_bootstrap5",
    "django_tables2",
    "star_ratings",
    "django_comments_xtd",
    "django_comments",
    "import_export",
    # project apps
    "apps.base",
    "apps.search",
    "apps.notice",
    "apps.event",
    "apps.news",
    "apps.blog",
    "apps.popup",
    "apps.page",  # static page
    "apps.partner",
    "apps.industry",
    "apps.survey",
    "apps.submit",  # form page
    "apps.course",
    "apps.program",
    "apps.ncs",
    "apps.flex",
    # "catalog",
    "apps.portal",
]

MIDDLEWARE = [
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "wagtail.contrib.redirects.middleware.RedirectMiddleware",
]

ROOT_URLCONF = "portal.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [
            os.path.join(PROJECT_DIR, "templates"),
        ],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                # django-tables2
                "django.template.context_processors.request",
            ],
        },
    },
]

WSGI_APPLICATION = "portal.wsgi.application"


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": os.path.join(BASE_DIR, "db.sqlite3"),
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = "ko-kr"

TIME_ZONE = "Asia/Seoul"

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATICFILES_FINDERS = [
    "django.contrib.staticfiles.finders.FileSystemFinder",
    "django.contrib.staticfiles.finders.AppDirectoriesFinder",
]

STATICFILES_DIRS = [
    Path(BASE_DIR) / "apps/comments_xtd/django_comments_xtd/static",
    os.path.join(PROJECT_DIR, "static"),
]

# ManifestStaticFilesStorage is recommended in production, to prevent outdated
# JavaScript / CSS assets being served from cache (e.g. after a Wagtail upgrade).
# See https://docs.djangoproject.com/en/4.2/ref/contrib/staticfiles/#manifeststaticfilesstorage
STATICFILES_STORAGE = "django.contrib.staticfiles.storage.ManifestStaticFilesStorage"

STATIC_ROOT = os.path.join(BASE_DIR, "static")
STATIC_URL = "/static/"

MEDIA_ROOT = os.path.join(BASE_DIR, "media")
MEDIA_URL = "/media/"


# Wagtail settings

WAGTAIL_SITE_NAME = "portal"

# Search
# https://docs.wagtail.org/en/stable/topics/search/backends.html
WAGTAILSEARCH_BACKENDS = {
    "default": {
        "BACKEND": "wagtail.search.backends.database",
    }
}

# Base URL to use when referring to full URLs within the Wagtail admin backend -
# e.g. in notification emails. Don't include '/admin' or a trailing slash
WAGTAILADMIN_BASE_URL = "http://example.com"

LOCALE_PATHS = (
    Path(BASE_DIR) / "apps/comments_xtd/django_comments_xtd/conf/locale",
    Path(BASE_DIR) / "conf" / "locale",
)

CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
    },
    "treenode": {
        "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
    },
}

# crispy
CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap5"
CRISPY_TEMPLATE_PACK = "bootstrap5"

# hitcount
HITCOUNT_KEEP_HIT_ACTIVE = {"hours": 1}

# start-rating
STAR_RATINGS_STAR_HEIGHT = 24

# sites
SITE_ID = 1

COMMENTS_APP = "django_comments_xtd"
COMMENTS_XTD_MAX_THREAD_LEVEL = 1
COMMENTS_XTD_MAX_THREAD_LEVEL_BY_APP_MODEL = {}
COMMENTS_XTD_CONFIRM_EMAIL = False
COMMENTS_XTD_LIST_ORDER = ("-thread_id", "order")
COMMENTS_XTD_APP_MODEL_OPTIONS = {
    "default": {
        "allow_flagging": False,
        "allow_feedback": True,
        "show_feedback": True,
        "who_can_post": "users",  # Valid values: 'all', users'
    }
}
COMMENTS_XTD_API_GET_USER_AVATAR = "comments_xtd.utils.get_user_avatar"

BASE_DOMAIN = "localhost"
BASE_PORTAL = ("portal.PORTAL", "포털")
PAGE_CONTENT = (
    ("notice.NoticeHome", "공지 사항"),
    ("event.EventHome", "이벤트"),
    ("news.NewsHome", "뉴스"),
    ("blog.BlogHome", "블로그"),
    ("popup.PopupHome", "팝업"),
    ("page.PageHome", "페이지"),
    ("partner.PartnerHome", "파트너"),
    ("industry.IndustryHome", "교육 분야"),
    ("survey.SurveyHome", "설문 조사"),
    ("submit.SubmitHome", "양식"),
    ("course.CourseHome", "과정"),
    ("program.ProgramHome", "프로그램"),
    ("flex.FlexHome", "플렉스"),
)

# import_export
IMPORT_EXPORT_SKIP_ADMIN_LOG = True
IMPORT_EXPORT_TMP_STORAGE_CLASS = CacheStorage
IMPORT_EXPORT_FORMATS = [XLSX]

DEFAULT_AUTO_FIELD = "django.db.models.AutoField"
