# Generated by Django 4.2.9 on 2024-01-15 02:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0005_blogpagethumbnailimage_delete_blogthumbnailimage"),
    ]

    operations = [
        migrations.RenameField(
            model_name="blogpagethumbnailimage",
            old_name="page",
            new_name="blog",
        ),
    ]
