# Generated by Django 4.2.9 on 2024-01-07 16:50

import apps.base.blocks
from django.db import migrations, models
import django.db.models.deletion
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("wagtailcore", "0089_log_entry_data_json_null_to_object"),
    ]

    operations = [
        migrations.CreateModel(
            name="Portal",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "content",
                    wagtail.fields.StreamField(
                        [
                            (
                                "banner",
                                wagtail.blocks.StructBlock(
                                    [
                                        (
                                            "slides",
                                            wagtail.blocks.StreamBlock(
                                                [
                                                    (
                                                        "slide",
                                                        wagtail.blocks.StructBlock(
                                                            [
                                                                (
                                                                    "image",
                                                                    wagtail.images.blocks.ImageChooserBlock(
                                                                        label="이미지"
                                                                    ),
                                                                ),
                                                                (
                                                                    "description",
                                                                    wagtail.blocks.RawHTMLBlock(
                                                                        label="HTML",
                                                                        required=False,
                                                                    ),
                                                                ),
                                                            ],
                                                            label="슬라이드",
                                                        ),
                                                    )
                                                ],
                                                collapsed=True,
                                                label="슬라이드",
                                            ),
                                        ),
                                        (
                                            "height",
                                            wagtail.blocks.ChoiceBlock(
                                                choices=[
                                                    ("300", "300px"),
                                                    ("400", "400px"),
                                                    ("500", "500px"),
                                                    ("600", "600px"),
                                                    ("700", "700px"),
                                                    ("800", "800px"),
                                                ],
                                                label="슬라이더 높이 px",
                                            ),
                                        ),
                                        (
                                            "fit_container",
                                            wagtail.blocks.BooleanBlock(
                                                label="container에 맞추기", required=False
                                            ),
                                        ),
                                    ],
                                    label="배너",
                                    required=False,
                                ),
                            ),
                            (
                                "page_content",
                                wagtail.blocks.StreamBlock(
                                    [
                                        (
                                            "page_content",
                                            wagtail.blocks.StructBlock(
                                                [
                                                    (
                                                        "model_string",
                                                        wagtail.blocks.ChoiceBlock(
                                                            choices=[
                                                                (
                                                                    "notice.NoticeHome",
                                                                    "공지 사항",
                                                                ),
                                                                (
                                                                    "event.EventHome",
                                                                    "이벤트",
                                                                ),
                                                                ("news.NewsHome", "뉴스"),
                                                                (
                                                                    "blog.BlogHome",
                                                                    "블로그",
                                                                ),
                                                                (
                                                                    "popup.PopupHome",
                                                                    "팝업",
                                                                ),
                                                                (
                                                                    "page.PageHome",
                                                                    "페이지",
                                                                ),
                                                                (
                                                                    "partner.PartnerHome",
                                                                    "파트너",
                                                                ),
                                                                (
                                                                    "industry.IndustryHome",
                                                                    "교육 분야",
                                                                ),
                                                                (
                                                                    "survey.SurveyHome",
                                                                    "설문 조사",
                                                                ),
                                                                (
                                                                    "submit.SubmitHome",
                                                                    "양식",
                                                                ),
                                                                (
                                                                    "course.CourseHome",
                                                                    "과정",
                                                                ),
                                                                (
                                                                    "program.ProgramHome",
                                                                    "프로그램",
                                                                ),
                                                            ],
                                                            label="콘텐츠 타입",
                                                        ),
                                                    ),
                                                    (
                                                        "tag",
                                                        wagtail.blocks.ChoiceBlock(
                                                            choices=apps.base.blocks.tag_choices,
                                                            help_text="공란이면 최신 순으로 가져옵니다.",
                                                            label="태그",
                                                            required=False,
                                                        ),
                                                    ),
                                                    (
                                                        "count",
                                                        wagtail.blocks.IntegerBlock(
                                                            default=8, label="콘텐츠 수"
                                                        ),
                                                    ),
                                                    (
                                                        "description",
                                                        wagtail.blocks.RichTextBlock(
                                                            label="설명", required=False
                                                        ),
                                                    ),
                                                    (
                                                        "icon",
                                                        wagtail.images.blocks.ImageChooserBlock(
                                                            label="아이콘", required=False
                                                        ),
                                                    ),
                                                ],
                                                label="페이지 콘텐츠",
                                            ),
                                        )
                                    ],
                                    label="페이지 콘텐츠",
                                ),
                            ),
                            (
                                "richtext",
                                wagtail.blocks.RichTextBlock(
                                    label="에디터", required=False
                                ),
                            ),
                            (
                                "html",
                                wagtail.blocks.RawHTMLBlock(
                                    label="HTML 코드", required=False
                                ),
                            ),
                        ],
                        blank=True,
                        null=True,
                        use_json_field=True,
                        verbose_name="페이지 내용",
                    ),
                ),
                (
                    "footer",
                    wagtail.fields.StreamField(
                        [
                            (
                                "richtext",
                                wagtail.blocks.RichTextBlock(
                                    label="에디터", required=False
                                ),
                            ),
                            (
                                "html",
                                wagtail.blocks.RawHTMLBlock(
                                    label="HTML 코드", required=False
                                ),
                            ),
                        ],
                        blank=True,
                        null=True,
                        use_json_field=True,
                        verbose_name="푸터",
                    ),
                ),
            ],
            options={
                "verbose_name": "포털",
                "verbose_name_plural": "포털",
            },
            bases=("wagtailcore.page",),
        ),
    ]
