# Generated by Django 4.2.9 on 2024-01-11 06:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("support", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="supporthome",
            options={"verbose_name": "고객센터", "verbose_name_plural": "고객센터"},
        ),
    ]
